### ISSUE TITLE
Lighting issues

### ISSUE THREAD

**Issue by drache444444** [deviant-dev/ds-issues#10]
**Describe the bug**
Some textures flicker and some lighting effects dont seem to work properly.

**System** 
 HTC Vive & radeon rx580 GPU

**Additional context**
mostly in the main hall the pillars on the top galerie. but the first goddess scene seems off with the lightning (i assume its lightling outside) and looks too bright when theres no lightning (if that makes sense)
![20200201082526_1](https://user-images.githubusercontent.com/60501223/73588982-24d44980-44d0-11ea-8990-99039c4158ba.jpg)

**Comment by drache444444** [comment]
Lighting in the godesses chamber seems fixed now

**Comment by deviant-dev** [comment]
It's not perfect, but lighting in the Entry should be more moody, less flickery at lower settings, and hopefully much improved.

**Comment by drache444444** [comment]
https://youtu.be/bF0pSE3Ccg0
video regarding this , recorded in steam release as of 2.12.2020 (mm.d.yyyy)

**Comment by HeadphoneTaco** [comment]
Issue is still present, but only on lower graphics settings (Low, Medium)

**Comment by asphyxiachan** [comment]
[capture from editor](https://gyazo.com/6c4d2ed423967f6409bea52842ed7aef)

low settings on a GTX 1080 TI look acceptable, might need testing from a radeon card on latest graphics drivers to confirm if this is still happening.  (2.1.1)

**Comment by HeadphoneTaco** [comment]
@asphyxiachan When you tested on the 1080, was that in VR or M+KB?

**Comment by HeadphoneTaco** [comment]
Keeping report open, as reference point for other lighting and minor cosmetic concerns

**Comment by HeadphoneTaco** [comment]
Closing, as this issue is old, and likely resolved in newer builds
